[package]
namespace = "morphine"
name = "VampireDB"
versionNumber = "0.1.0"
description = "Stupid simple wrapper for LiteDB"
websiteUrl = "https://github.com/phlebotomist/VampireDB"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.733.2"
deca-VampireCommandFramework = "0.10.2"

[build]
icon = "./logo.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./bin/Debug/net6.0/VampireDB.dll"
target = "VampireDB.dll"

[[build.copy]]
source = "./bin/Debug/net6.0/LiteDB.dll"
target = "LiteDB.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["v-rising"]

[publish.categories]
v-rising = ["oakveil-update", "mods", "server"]